import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LearnPanel from "../components/learn-panel";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const mainRef = React.useRef<HTMLDivElement>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ textAlign: "center", marginBottom: 0, fontSize: "1.6rem" }}>
        Learn Panel
      </h1>
      <p style={{ textAlign: "center" }}>
        try opening the book icon and moving the slides panel.
      </p>
      <main className={styles.main} ref={mainRef}>
        <LearnPanel bounds={mainRef} />
      </main>
    </div>
  );
};

export default Home;
